default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: your_app_development
  username: your_username
  password: your_password
  host: localhost

test:
  <<: *default
  database: your_app_test
  username: your_username
  password: your_password
  host: localhost

production:
  <<: *default
  database: your_app_production
  username: your_username
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
